version: 0.2
phases:
  pre_build:
    commands:
      - bundle
  build:
    commands:
      - middleman build
  post_build:
    commands:
      - aws s3 sync build/ s3://threat-response-cloud/
      - aws cloudfront create-invalidation --distribution-id E13J2919BK92B1 --paths /*
